# backend/app/models/template.py (Updated)
from sqlalchemy import Column, String, DateTime, Text, Boolean, JSON, Integer
from sqlalchemy.orm import relationship
from ..database import Base
from datetime import datetime
import uuid

class Template(Base):
    __tablename__ = "templates"
    
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    name = Column(String, nullable=False)
    description = Column(Text)
    original_filename = Column(String)
    category = Column(String, default="general")
    file_path = Column(String, nullable=False)
    
    # Template metadata from parser
    placeholders = Column(JSON)  # List of all placeholder fields
    schema = Column(JSON)        # Form schema generated by parser
    
    # Field assignment configuration
    field_assignments = Column(JSON)  # Which fields are filled by whom
    # Structure: {"student_fields": ["nama", "nim"], "admin_fields": ["nomor", "tanggal"]}
    
    # Template settings
    is_active = Column(Boolean, default=True)
    requires_admin_review = Column(Boolean, default=True)
    auto_generate_fields = Column(JSON)  # Fields that are auto-generated (like dates, numbers)
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Usage statistics
    usage_count = Column(Integer, default=0)
    
    # Relationships
    requests = relationship("LetterRequest", back_populates="template")